workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ReminderApp.xcodeproj"
        XCODE_SCHEME: "ReminderApp"
      xcode: latest
    scripts:
      - name: List files to debug
        script: |
          echo "Current directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Looking for Xcode project:"
          find . -name "*.xcodeproj" -type d
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
